spring:
  application:
    name: security-service
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/securityservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: security_service
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql

server:
  port: 9091
